source = 'mqtt://edge_broker:1883?client_id=mls_proxy.1'
sink = 'mqtt://fog_broker:1883?client_id=mls_proxy.1'
log_level = "debug"
label_key = { path = '/usr/local/etc/mls/data/label.key', id = 'proxy.label.1' }
info_key = { path = '/usr/local/etc/mls/data/info.key', id = 'proxy.info.1' }
mls_topic = "mls/info"
threads = 2

[topics]
"hello" = 4
"hello2" = 4
"test" = 1
"hello0/test" = 0
"hello2/test" = 1
"hello2/test" = 2
"hello3/test" = 3
"hello4/test" = 4
